version: '3.8'
services:
  mysql:
    env_file:
      - .env
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
